#!/bin/bash
set -euo pipefail

# === Install required system packages ===
echo "=== Installing required packages ==="
sudo apt update
sudo apt install -y curl tar jq openssl ca-certificates gnupg apt-transport-https

# === Remove old kubernetes-xenial repo if present ===
sudo rm -f /etc/apt/sources.list.d/kubernetes.list
sudo rm -f /etc/apt/sources.list.d/kubernetes-xenial.list

# === Install kubectl via snap if missing ===
echo "=== Installing kubectl via snap ==="
if ! command -v kubectl &> /dev/null; then
    sudo snap install kubectl --classic
fi

# === Install K9s if missing ===
echo "=== Installing K9s if missing ==="
if ! command -v k9s &> /dev/null; then
    K9S_VERSION=$(curl -s https://api.github.com/repos/derailed/k9s/releases/latest | jq -r '.tag_name')
    curl -LO https://github.com/derailed/k9s/releases/download/${K9S_VERSION}/k9s_Linux_amd64.tar.gz
    tar xvf k9s_Linux_amd64.tar.gz
    sudo mv k9s /usr/local/bin/
    rm k9s_Linux_amd64.tar.gz
fi

# === Make 'k' command work immediately ===
echo "=== Making 'k' command work immediately ==="
alias k='microk8s kubectl'
export -f k
echo "Run 'k' now to launch K9s in this shell."

# === Ensure user is in microk8s group ===
echo "=== Ensuring user is in microk8s group ==="
sudo usermod -aG microk8s $USER
sudo chown -f -R $USER ~/.kube || true

# === Enable MicroK8s addons ===
echo "=== Enabling MicroK8s dashboard and ingress ==="
sudo microk8s enable ingress
sudo microk8s enable dashboard

# === Expose dashboard as NodePort ===
echo "=== Exposing Kubernetes Dashboard as NodePort ==="
sudo microk8s kubectl -n kube-system patch svc kubernetes-dashboard -p '{"spec": {"type": "NodePort"}}'

# === Wait for dashboard service to exist and get NodePort ===
echo "=== Waiting for Kubernetes Dashboard service ==="
until NODEPORT=$(sudo microk8s kubectl -n kube-system get svc kubernetes-dashboard -o jsonpath='{.spec.ports[0].nodePort}') && [ -n "$NODEPORT" ]; do
    echo "Waiting for dashboard NodePort..."
    sleep 2
done
DASHBOARD_IP=$(hostname -I | awk '{print $1}')
echo "Dashboard NodePort: https://${DASHBOARD_IP}:${NODEPORT}"

# === Ensure TLS secret for dashboard (auto-generated by MicroK8s) ===
echo "=== Ensuring TLS secret for dashboard ==="

# === Apply ingress for dashboard.local ===
echo "=== Applying ingress for dashboard.local ==="
cat <<EOF | sudo microk8s kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: dashboard.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
EOF

# === Update /etc/hosts ===
echo "=== Updating /etc/hosts with node IP for dashboard.local ==="
if ! grep -q "dashboard.local" /etc/hosts; then
    echo "${DASHBOARD_IP} dashboard.local" | sudo tee -a /etc/hosts
fi

# === Add dashboard.local cert to system trusted CA ===
echo "=== Adding dashboard.local cert to system trusted CA ==="
sudo microk8s kubectl -n kube-system get secret kubernetes-dashboard-certs -o jsonpath='{.data["tls\.crt"]}' | base64 -d | sudo tee /usr/local/share/ca-certificates/dashboard.local.crt
sudo update-ca-certificates

# === Generate Kubernetes Dashboard admin token ===
echo "=== Generating Kubernetes Dashboard admin token ==="
if ! sudo microk8s kubectl -n kube-system get sa dashboard-admin &>/dev/null; then
    sudo microk8s kubectl -n kube-system create sa dashboard-admin
    sudo microk8s kubectl create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=kube-system:dashboard-admin
fi

# === Retrieve token ===
TOKEN=$(sudo microk8s kubectl -n kube-system create token dashboard-admin 2>/dev/null || \
        sudo microk8s kubectl -n kube-system describe secret $(sudo microk8s kubectl -n kube-system get sa dashboard-admin -o jsonpath='{.secrets[0].name}') | grep '^token:' | awk '{print $2}')

echo "=== Kubernetes Dashboard admin token ==="
echo "${TOKEN}"

echo "=== K9s & Dashboard Setup Complete ==="
echo "Dashboard accessible at:"
echo "  NodePort: https://${DASHBOARD_IP}:${NODEPORT}"
echo "  Ingress : https://dashboard.local"
echo "Run 'k' to launch K9s immediately in this shell."
